// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeYk_uhHjnMKSLm-61jquabZkk_60Ym2Q',
    appId: '1:800223160362:web:d79d1c7255217a6825bb53',
    messagingSenderId: '800223160362',
    projectId: 'booke-6db00',
    authDomain: 'booke-6db00.firebaseapp.com',
    storageBucket: 'booke-6db00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiO_TSfvc4slIw73tGWWFrh87MXg2U4vs',
    appId: '1:800223160362:android:8f0ec2c9819c132825bb53',
    messagingSenderId: '800223160362',
    projectId: 'booke-6db00',
    storageBucket: 'booke-6db00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANi4TN3oTjwwJPiLhE-rFes8FAkXTQZO4',
    appId: '1:800223160362:ios:099e64e652a314c325bb53',
    messagingSenderId: '800223160362',
    projectId: 'booke-6db00',
    storageBucket: 'booke-6db00.appspot.com',
    iosClientId: '800223160362-sqaubuonlh12q7e1be0b50rsrut9edk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANi4TN3oTjwwJPiLhE-rFes8FAkXTQZO4',
    appId: '1:800223160362:ios:099e64e652a314c325bb53',
    messagingSenderId: '800223160362',
    projectId: 'booke-6db00',
    storageBucket: 'booke-6db00.appspot.com',
    iosClientId: '800223160362-sqaubuonlh12q7e1be0b50rsrut9edk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBook',
  );
}
